import { createSlice } from "@reduxjs/toolkit";

let initialState = {
    teamRank : [
        {
            ranking:"1",
            teamName:"LG",
            matchGame:"18",
            win:"15",
            lose:"3",
            draw:"0",
            winPercent:"0.833",
            "게임차":"0",
            recent10Game:"8승0무2패",
            winStraight:"1승",
            homeMatchResult:"10-0-1",
            awayMatchResult:"5-0-2"
        },
        {
            ranking:"2",
            teamName:"SSG",
            matchGame:"16",
            win:"9",
            lose:"7",
            draw:"0",
            winPercent:"0.563",
            "게임차":"5",
            recent10Game:"5승0무5패",
            winStraight:"2패",
            homeMatchResult:"6-0-2",
            awayMatchResult:"3-0-5"
        },
        {
            ranking:"3",
            teamName:"KT",
            matchGame:"18",
            win:"9",
            lose:"8",
            draw:"1",
            winPercent:"0.529",
            "게임차":"5.5",
            recent10Game:"5승0무5패",
            winStraight:"1패",
            homeMatchResult:"8-0-4",
            awayMatchResult:"1-1-4"
        },
        {
            ranking:"4",
            teamName:"SAMSUNG",
            matchGame:"19",
            win:"10",
            lose:"9",
            draw:"0",
            winPercent:"0.526",
            "게임차":"5.5",
            recent10Game:"4승0무6패",
            winStraight:"3패",
            homeMatchResult:"7-0-4",
            awayMatchResult:"3-0-5"
        },
        {
            ranking:"5",
            teamName:"LOTTE",
            matchGame:"20",
            win:"9",
            lose:"10",
            draw:"1",
            winPercent:"0.474",
            "게임차":"6.5",
            recent10Game:"5승0무5패",
            winStraight:"1승",
            homeMatchResult:"4-1-5",
            awayMatchResult:"5-0-5"
        },
        {
            ranking:"6",
            teamName:"HANHWA",
            matchGame:"20",
            win:"9",
            lose:"11",
            draw:"0",
            winPercent:"0.450",
            "게임차":"7",
            recent10Game:"6승0무4패",
            winStraight:"2승",
            homeMatchResult:"4-0-4",
            awayMatchResult:"5-0-7"
        },
        {
            ranking:"7",
            teamName:"KIA",
            matchGame:"18",
            win:"8",
            lose:"10",
            draw:"0",
            winPercent:"0.444",
            "게임차":"7",
            recent10Game:"5승0무5패",
            winStraight:"2승",
            homeMatchResult:"5-0-5",
            awayMatchResult:"3-0-5"
        },
        {
            ranking:"8",
            teamName:"NC",
            matchGame:"16",
            win:"7",
            lose:"9",
            draw:"0",
            winPercent:"0.438",
            "게임차":"7",
            recent10Game:"4승0무6패",
            winStraight:"1승",
            homeMatchResult:"1-0-4",
            awayMatchResult:"6-0-5"
        },
        {
            ranking:"9",
            teamName:"DOOSAN",
            matchGame:"19",
            win:"8",
            lose:"11",
            draw:"0",
            winPercent:"0.421",
            "게임차":"7.5",
            recent10Game:"5승0무5패",
            winStraight:"1승",
            homeMatchResult:"4-0-4",
            awayMatchResult:"4-0-7"
        },
        {
            ranking:"10",
            teamName:"KIWOOM",
            matchGame:"20",
            win:"7",
            lose:"13",
            draw:"0",
            winPercent:"0.350",
            "게임차":"9",
            recent10Game:"3승0무7패",
            winStraight:"2패",
            homeMatchResult:"4-0-5",
            awayMatchResult:"3-0-8"
        }
    ],
};

const teamRankSlice = createSlice({
    name: 'teamRank',
    initialState,
    reducers: {

    }
});

export default teamRankSlice.reducer;